services:
  name-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=DEBUG
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
