version: '3.8'

services:
  name-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Enable debug logging
      - LOG_LEVEL=DEBUG
    # Resource constraints matching KServe requirements
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
